name: Compile and Push RuleSet

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *' # 每天在 UTC 时间 3:00 AM 运行

jobs:
  build-and-push-ruleset:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests # 如果你的Python脚本需要额外的库
        
    - name: Generate JSON Configs
      run: python main.py # 运行 main.py 来生成 JSON 文件

    - name: Install sing-box
      run: |
        wget https://github.com/SagerNet/sing-box/releases/download/v1.8.8/sing-box-1.8.8-linux-amd64.tar.gz
        tar -xzf sing-box-1.8.8-linux-amd64.tar.gz
        echo "$PWD/sing-box-1.8.8-linux-amd64" >> $GITHUB_PATH

    - name: Compile JSON to SRS
      run: |
        for file in $(ls *.json); do
          ./sing-box-1.8.8-linux-amd64/sing-box rule-set compile --output "${file%.json}.srs" "$file"
        done

    - name: Commit and Push
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add *.srs
        git commit -m "Auto-update ruleset"
        git push origin HEAD:ruleset # Assuming your branch is named ruleset
