name: Compile and Push RuleSet

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # 每天在 GMT+8 时间 8:00 AM 运行

jobs:
  build-and-push-ruleset:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Read Sing-Box version
      run: |
        echo "SING_BOX_VERSION=$(cat version.txt)" >> $GITHUB_ENV

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Generate JSON Configs
      run: python main.py # 运行 main.py 来生成规则的 JSON 文件

    - name: Install sing-box
      run: |
        wget https://github.com/SagerNet/sing-box/releases/download/v${{ env.SING_BOX_VERSION }}/sing-box-${{ env.SING_BOX_VERSION }}-linux-amd64.tar.gz
        tar -xzf sing-box-${{ env.SING_BOX_VERSION }}-linux-amd64.tar.gz
        echo "$PWD/sing-box-${{ env.SING_BOX_VERSION }}-linux-amd64" >> $GITHUB_PATH

    - name: Compile JSON to SRS
      run: |
        for file in $(ls *.json); do
          ./sing-box-${{ env.SING_BOX_VERSION }}-linux-amd64/sing-box rule-set compile --output "${file%.json}.srs" "$file"
        done

    - name: Commit and Push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # 设置Git用户信息
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        # 移动srs文件到新文件夹
        mkdir ruleset
        mv *.srs ruleset
        cd ruleset
        # 上传二进制规则
        git init
        git remote add origin https://github-action:$GITHUB_TOKEN@github.com/DDCHlsq/sing-ruleset.git
        git branch -M ruleset
        git add .
        git commit -m "Update ruleset"
        git push -f origin ruleset
